#include "input_mgmt.h"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

char    *help = "Usage: %s -m mode -n filename [-f number] [-t number] [-y precise number] [-z precise number] [-c number] [-r number] (-h/help)\n"
                "m - mode [read/write]\n"
                "n - name of the file program is supposed to save/ read from [name]\n"
                "f - from which vertex the dijkstra algorithm starts (only in read mode) [number]\n"
                "t - to which vertex the dijkstra algorithm finds way (only in read mode) [number]\n"
                "y - bottom limit of generated paths weight (default: 0) [precise number]\n"
                "z - top limit of generated paths weight (default: 1) [precise number]\n"
                "c - number of columns in graph generated by the program (only in write mode) [number]\n"
                "r - number of rows in graph generated by the program (only in write mode) [number]\n"
                "h/help - display help request\n";

void view_help(char *progname)
{
    printf(help, progname);
    exit(EXIT_FAILURE);
}

void input_errors_management(char *mode, int fromvert, int tovert, char *filename, double fromrange, double torange, char *progname, int rows, int columns)
{
    if(torange > fromrange) //if fromrange and torange confused, swap them
    {
        double buf = torange;
        torange = fromrange;
        fromrange = buf;
    }

    if(filename == NULL && mode == NULL)
    {
        printf("Too few launch arguments! Launch instructions:\n");
        view_help(progname);
    }

    if(filename == NULL) // If file not given, exit program
    {
        printf("File name not given! Ending program...\n");
        exit(EXIT_FAILURE);
    }

    if(strcmp(mode, "read") != 0 && strcmp(mode, "write") != 0) // As in error messages respectively
    {
        printf("Program mode (read/write) invalid! Ending program...\n");
        exit(EXIT_FAILURE);
    }

    if((fromvert == -1 || tovert == -1) && strcmp(mode, "read") == 0)
    {
        printf("Dijkstra vertexes not given! Ending program...\n");
        exit(EXIT_FAILURE);
    }

    if((columns == -1 || rows == -1) && strcmp(mode, "write") == 0)
    {
        printf("Number of rows or columns not given! Ending program...\n");
        exit(EXIT_FAILURE);
    }
}